name: Build README.md

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
      # We need the full history to in order to inspect created/updated.
      with:
        fetch-depth: 0  
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - uses: actions/cache@v2
      name: Configure pip caching
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install Python dependencies
      run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Update README.md
      run: |-
        python update_readme.py --rewrite
        cat README.md
    - name: Commit and push README.md (if changed)
      run: |-
        git diff
        git config --global user.name "readme-bot"
        git config --global user.email "actions@users.noreply.github.com"
        git add README.md
        git commit -m "This is an automated update of README.md." || exit 0
        git push
